name: test-cxx20

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        compiler: [[clang, clang++], [gcc, g++]]
        enable_assertion: [ON, OFF]
        include:
          - os: windows-latest
            compiler: [cl, cl]
            enable_assertion: ON
          - os: windows-latest
            compiler: [cl, cl]
            enable_assertion: OFF
    env:
      proj_type: ${{ (matrix.os == 'windows-latest' && matrix.compiler[0] != 'cl') && '-G "MinGW Makefiles"' || '' }}

    steps:
      - uses: actions/checkout@v4
      - name: set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: configure CMake
        run: >
          cmake ${{ env.proj_type }}
          -B ${{ github.workspace }}/build -S ${{ github.workspace }}
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER=${{ matrix.compiler[0] }}
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler[1] }}
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
          -DALWAYS_ENABLE_ASSERTION=${{ matrix.enable_assertion }}
      - name: build
        run: cmake --build ${{ github.workspace }}/build --config Release --parallel 10
      - name: test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --output-on-failure --build-config Release --parallel 10
