name: test-cxx20

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        os: [windows-latest, ubuntu-latest]
        c_compiler: [clang, gcc, cl]
        exclude:
          - os: ubuntu
            c_compiler: cl
    
    steps:
      - uses: actions/checkout@v4
      - name: set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}/test
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
      - name: build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
      - name: test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}
